### ISSUE TITLE
Is it supported Vue3.x

### ISSUE THREAD

**Issue by Moveharder** [kazupon/vue-i18n#1024] opened 2020-10-26 05:59 UTC
### Bug
i can't use i18n in my vue3.0 project, is it support?

### vue & vue-i18n version
ex: 3.0.0, 8.22.1

### What is Expected?
Wanna use vue-i18n in my Vue3.x Project.

### What is actually happening?
Error happened like this : 
uncaught TypeError: Cannot read property 'config' of undefined
    at VueI18n._initVM (vue-i18n.esm.js?5c2e:1314)
    at new VueI18n (vue-i18n.esm.js?5c2e:1253)
    at eval

**Comment by exoego** [comment] 2020-10-26 06:05
No.

**Comment by exoego** [comment] 2020-10-26 06:11
Closing as duplicate of #1004

**Closed by exoego** 2020-10-26 06:11 UTC
