### ISSUE TITLE
Directive destroyed before animation end

### ISSUE THREAD

**Issue by ar53n** [kazupon/vue-i18n#408] opened 2018-08-08 08:12 UTC
### vue & vue-i18n version
ex: 2.5.16, 8.0

### Steps to reproduce
![hide_directive](https://user-images.githubusercontent.com/7085102/43824815-b4a455bc-9afb-11e8-832c-30b28761772e.gif)

### What is Expected?
When using non-directive way its work correctly.

**Comment by kimuraz** [comment] 2018-08-09 11:52
Can you add a reproduction link?

I couldn't reproce it: `https://codepen.io/kimuraz/pen/jpQRjb`

**Comment by ar53n** [comment] 2018-08-09 13:08
@kimuraz https://codepen.io/anon/pen/ejQqvp. Thank you for reproduce link. Just i changed v-show to `v-if`. But in my project used `router-view`.

**Comment by kimuraz** [comment] 2018-08-09 19:06
@ar53n I think that, in this case, the problem is the `v-if` because the transition is for `opacity` property. When you use `v-if` you are removing the element from the DOM, instead of doing it, the `v-show` directive actually hides an element changing its `opacity`

**Comment by kimuraz** [comment] 2018-08-17 11:58
@ar53n I guess that this issues is due to which order the directives are resolved in VueJS transitions ([see this](https://github.com/vuejs/vue/blob/5191f13472d1fc37bdd601079970201fde6bf13e/src/platforms/web/runtime/transition-util.js#L108)). Since it seems to be async because of the timeout, while it doesn't resolves, the `v-t` directive resolves with `v-if / v-show`. Although I'm not sure, let me know if you go on solving this problems.

**Comment by connected** [comment] 2018-10-05 07:54
It was not an issue on version 7.8.0, see https://codepen.io/madhamster/pen/ReRxBL
Possible solution is to lock version in package.json

IMO this is def. a plugin bug not vue.

**Comment by bponomarenko** [comment] 2018-12-29 13:00
I have added PR #495 which suppose to fix this issue. @ar53n @connected @thariddler will this work for you?

**Closed** 2019-01-02 15:00 UTC
Labels: good first issue, help wanted, improvement

**Comment by rchl** [comment] 2019-02-12 15:18
I've just noticed this problem and then found the solution that works for me, but I do wonder about the downsides of using the solution (using global `preserveDirectiveContent` setting). Nowhere in the documentation I can find any mention of cons so I wonder why it's not enabled by default.

I have noticed this problem with Nuxt and without even using transitions. Just clicking a nuxt-link (router-link) causes text to disappear from page before navigating to new page. I believe it's either due to `asyncData` or nuxt-i18n locale handling but either way, the question is why is that not enabled by default.

**Comment by rchl** [comment] 2019-02-25 12:52
@kazupon any comments?

**Comment by kazupon** [comment] 2019-02-26 05:16
@rchl 
It's backward compatibility.

@bponomarenko said in #495
>`preserveDirectiveContent` is false by default to remain backward compatibility. In the future (if there will be demand for it) it can be set to true by default, but that would be a breaking change.

**Comment by rchl** [comment] 2019-02-26 08:45
It doesn't really answer my question. What exactly does/can it break? Is it just to be on the safe side, because the behaviour is slightly different? Any specific issues are to be expected @bponomarenko?

**Comment by bponomarenko** [comment] 2019-02-26 10:46
@rchl Hi Rafał

I would consider this change to be a "breaking change" because it changes functionality of the library – after directive destroy content will be preserved instead of cleaned up. It may not break someones project, but can result in different behaviour if that project, let say, has some logic around presence of the content inside text blocks. How rationale this logic is is another discussion but, in my experience, sometimes developers can just implement hacks for a solution to work.

Taking this into consideration, and general best practices for packages versioning, it would require to bump major library version in order to enable `preserveDirectiveContent` feature by default. I didn't do that in my PR because major releases usually take more time to publish, as they tend to aggregate multiple breaking changes. However, to be able to use this functionality faster – I added this feature turned off  by default (preserving original library behaviour), so only minor version bump were required.

If you really need this feature to be turned on by default, I believe the best would be creating different issue specific to this request. Which can be satisfied in the next major update, but that is up to the library author.

**Comment by rchl** [comment] 2019-02-26 13:00
Yes, that is more or less what I've expected to hear.

I can enable it myself so I'm fine here but I agree that it should be on the roadmap for enabling on next major version as otherwise basic functionality of Vue breaks.
And for Nuxt it also makes for some ugly visual behaviour in some cases.
