### ISSUE TITLE
mergeLocalMessage broken?

### ISSUE THREAD

**Issue by websanova** [kazupon/vue-i18n#1108] opened 2021-01-29 04:09 UTC
Using merge after some delay does not seem to trigger an update.

> Works

```
Vue.i18n.mergeLocaleMessage('en-US', {test: {one: 'one'}});
Vue.i18n.mergeLocaleMessage('en-US', {test: {two: 'two'}});
```

> Does not work

```
Vue.i18n.mergeLocaleMessage('en-US', {test: {one: 'one'}});

setTimeout(() => {
    // trying to output {{ $t('test.two') }} does not work it never triggers in this case...
    Vue.i18n.mergeLocaleMessage('en-US', {test: {two: 'two'}});
}, 2000);
```

> Works with "set"...

```
Vue.i18n.mergeLocaleMessage('en-US', {test: {one: 'one'}});

setTimeout(() => {
    Vue.i18n.setLocaleMessage('en-US', {test: {one: 'one', two: 'two'}});
}, 2000);
```

**EDIT: Not sure if it's related to latest change https://github.com/kazupon/vue-i18n/issues/1099 ?**

**Comment by phonezawphyo** [comment] 2021-07-16 10:16
I can confirm it is a bug due to #1099 and should be fixed asap.
Added a PR. https://github.com/kazupon/vue-i18n/pull/1321

**Comment by kazupon** [comment] 2021-10-31 06:11
close, as reason, vue-i18n was released.

Thanks

**Closed by kazupon** 2021-10-31 06:11 UTC
Labels: help wanted, Status: PR Welcome
