### ISSUE TITLE
Html "lang" attribute doesn't change upon changing "locale"

### ISSUE THREAD

**Issue by onurusluca** [kazupon/vue-i18n#975] opened 2020-08-14 22:07 UTC
### vue & vue-i18n version
ex: 2.1.0, 5.0

**Comment by exoego** [comment] 2020-08-15 00:02
Please respect the issue template and provide enough information to repro/investigate issue.

From limited info, this seems a duplicate of https://github.com/kazupon/vue-i18n/issues/447

Feel free to reopen when enough information is entered.

**Closed by exoego** 2020-08-15 00:02 UTC
