### ISSUE TITLE
i18n falls back to translate but key actually exists

### ISSUE THREAD

**Issue by Christilut** [kazupon/vue-i18n#89] opened 2016-11-20 15:31 UTC
### vue & vue-i18n version
Vue 2.0.8
Vue-i18n 4.7.2
Chrome 54, IE11, Firefox 49

### Steps to reproduce
I'll reproduce on request (if I can manage, seems like an odd bug).

### What is Expected?
No warnings

### What is actually happening?
A single $t() is not being translated but goes to fall back language instead.

More info:
I load multiple json files eg `nl-NL.json` and `en-US.json` with a bunch of strings for the entire website. This works perfectly expect for 1 single instance. When I put the language on `nl-NL`, it will always fallback to `en-US` for this one string (always the same). The rest of the website is correctly translated.
Both json files contain the correct key value. 

Getting the following warning when this happens:
```
vue-i18n.common.js?2c49:26 [vue-i18n] Fall back to translate the keypath "infobar_start_season" with "en-US" language.
```

The template is (originally in Jade/Pug):
```jade
    div(v-if='!open')
      p(v-if='isSeasonOver') {{ $t('infobar_start_season', season.startMonth, season.startDay) }}
      p(v-else) {{ $t('infobar_open_nextday') }}
```
or converted to HTML:
```html
<div v-if="!open">
  <p v-if="isSeasonOver">{{ $t('infobar_start_season', season.startMonth, season.startDay) }}</p>
  <p v-else="v-else">{{ $t('infobar_open_nextday') }}</p>
</div>
```

And the `en-US` string inside the json is:
```
  "infobar_start_season": "Our season will start on {0} {1}",
```
The `nl-NL` one is the same except different language.

**Comment by Christilut** [comment] 2016-11-20 15:50
Fixed some (seemingly unrelated) bugs in IE/Firefox, this bug now occurs there too.

**Comment by kazupon** [comment] 2016-11-20 17:14
Thank you for your reporting!
I tried to reproduce from your feedback info.
http://jsfiddle.net/kazupon/f9khsu2q/3/

However, I cannot reproduce your reporting state.
Can you provide the minimum reporo code with jsfiddle (or other) please?

**Comment by Christilut** [comment] 2016-11-20 18:45
I honoustly don't know how to reproduce this. I can send you my project. Could you send me a mail at christilut@gmail.com or let me know what your preferred way to get the project is.

**Comment by Christilut** [comment] 2016-11-20 20:04
Actually, I dug a bit more and tried some random things... 
http://jsfiddle.net/rj0qxd78/
Check out the commented 2 lines. They should both work but the one with a string doesn't. Might be related to my original problem.

**Comment by jmaister** [comment] 2017-08-13 00:16
I reproduced this same error.

The language defined in my browser is es-ES. I defined 'en', 'es' in vue-i18n config.

The fallbackLocale goes to 'en', but I would expect it to use 'es'.

i.e.
1st option -> es-ES
2nd option -> es
3rd option -> whatever is in fallbackLocale

**Comment by vanoorschot** [comment] 2017-09-08 12:03
I've had the same issue.
The "Fall back to translate the keypath" error disappears when I use $te instead of $t.

**Comment by gangsthub** [comment] 2017-09-11 18:31
`[vue-i18n] Fall back to translate the keypath 'pages.home' with 'es' locale.` That's been requested by my error page. But that prompted in the building time. I think this must to be with the routing generation at build time.

**Comment by ChadTaljaardt** [comment] 2017-10-23 13:51
Any update on this? I'm getting the same issue here.

**Comment by gangsthub** [comment] 2017-11-04 02:33
This seems to be more related to SSR:

https://github.com/kazupon/vue-i18n/commit/5f6b271#diff-45ed5e0f20f4e0ac60d2fe09f79cafa0R57

We will to have a look at the methods of using custom directive for SSR:

https://github.com/kazupon/vue-i18n/tree/dev/examples/ssr

**Comment by pbirkoff** [comment] 2017-11-14 11:44
I ran into the same problem. It appears to happen when using the formatting option. When using 'List formatting', be sure to provide an array with the values, in stead of separate options, e.g.  $t('infobar_start_season', [season.startMonth, season.startDay]) }} This solved my problem.

**Comment by ifraixedes** [comment] 2017-11-30 18:59
For me this issue is similar to #49 
We got a similar problem that the one expressed here and in #49 
I posted how we fixed in https://github.com/kazupon/vue-i18n/issues/49#issuecomment-348285830

**Comment by kazupon** [comment] 2018-06-24 05:39
close due to in-activity

**Closed by kazupon** 2018-06-24 05:39 UTC
Labels: need more repro

**Comment by Leslie-Wong-H** [comment] 2022-06-20 00:56
Using en and zh would cause the warning, while "en-US" and "zh-CN" wouldn't. 

vue-i18n: "^8.27.1"

```js
/**
 * Get the browser language
 */
export const browserLang = (() => {
  const supports = ["en", "zh"];
  const langs = {
    zh: "zh-CN",
    en: "en-US",
  };
  const userLang = window.navigator.language || window.navigator.userLanguage;
  let lang = supports[0];
  if (userLang) {
    const useLang = userLang.trim().slice(0, 2);
    if (useLang in langs) {
      lang = useLang;
    }
  }
  return langs[lang];
})();

const i18n = new VueI18n({
  locale: browserLang,
  // Using en and zh would cause the warning, while "en-US" and "zh-CN" wouldn't.
  // messages: { en: translationEN, zh: translationCN },
  messages: { "en-US": translationEN, "zh-CN": translationCN },
});
```
