### ISSUE TITLE
Cannot read property 'locale' of undefined

### ISSUE THREAD

**Issue by WangShayne** [kazupon/vue-i18n#118] opened 2017-03-02 17:10 UTC
Hi.I use the vue-router with vue-i18n together,when i changed the path,chrome remind a issue 
![image](https://cloud.githubusercontent.com/assets/17644818/23518277/e478538c-ffad-11e6-8a58-07b643024d50.png)

my i18n.js
```
import Vue from 'vue'
import VueI18n from 'vue-i18n'
import cn from './zh-CN.json'
import jh from './zh-JH.json'
import store from '../store'

Vue.use(VueI18n)

export default new VueI18n({
  locale: 'zh-JH',
  messages: {
    'zh-CN': cn,
    'zh-JH': jh
  }
})
```

### vue & vue-i18n version
    ```"vue": "^2.1.0",
    "vue-i18n": "^6.0.0-alpha.2",
    "vue-router": "^2.0.1",```

**Comment by gary149** [comment] 2017-03-03 18:07
+ 1

**Comment by gary149** [comment] 2017-03-03 18:07
Same issue here

**Comment by groundc** [comment] 2017-03-04 23:02
Same issue

**Comment by kazupon** [comment] 2017-03-05 01:01
@WangShayne 
Sorry, for replying for late.
Hmm 🤔 , I cannot debug with your issue reporting.
Could you provide the minimum reproduction repo please?

**Comment by WangShayne** [comment] 2017-03-05 08:10
@kazupon 
Thanks for you replay.
Sorry,because the project is urgent,I change the plugin to vuex-i18n.
When I first used "npm run dev", the project was running normally, but I did not know when to start, when I switch the path, it will prompt this error.

@gary149  @groundc 
Can you provide more useful information?thanks

**Comment by CommanderXL** [comment] 2017-03-05 16:40
same issue here.

It looks like when using `Vue.use(VueI18n)`. 

It doesn't load for Vue。So Vue don't have the methods defined in VueI18n.

**Comment by CommanderXL** [comment] 2017-03-05 16:43
I have a minimum repo:

https://github.com/CommanderXL/x-blog

branch:  i18n

**Comment by sunyouwei** [comment] 2017-03-06 00:13
@kazupon
same issue here.

**Comment by lauer3912** [comment] 2017-03-06 00:34
@kazupon 
same issue here.

**Comment by lauer3912** [comment] 2017-03-06 00:35
@kazupon 
  "dependencies": {
    "vue": "^2.2.1",
    "vue-i18n": "^6.0.0-alpha.2",
    "vue-router": "^2.3.0",
    "vuex": "^2.2.1"
  },

**Comment by kazupon** [comment] 2017-03-06 03:01
Hmm 🤔 , I tried to reproduce the below repo, but I could not repdocuce it.  😞 
https://github.com/kazupon/vue-i18n-alpha-repro

@WangShayne 
>when I switch the path

Would you tell me the detail it?

@CommanderXL 
Thanks for your reproduction repo!
However, I could not found `i18n` branch in your repo.
Could you push `i18n` branch to it?

**Comment by CommanderXL** [comment] 2017-03-06 03:49
@kazupon Well. You can use master branch. I just push the code.

**Comment by kazupon** [comment] 2017-03-06 08:09
@CommanderXL 
Thank you for your pushing!
In you latest commits of `master` branch, I didn't found `vue-i18n` dependencies. 😞 
https://github.com/CommanderXL/x-blog/commit/dc96765af5e28b7b0601caa1971d4ad30298928b

Where your implementation with `vue-i18n` ?

**Comment by CommanderXL** [comment] 2017-03-06 10:14
@kazupon Well. You can install the npm package.json in your local. Then `npm run dev`

Well. In your demo:
https://github.com/kazupon/vue-i18n-alpha-repro

It works well.

As I see, the demo config file is different with the config file  https://kazupon.github.io/vue-i18n/started.html showed on the gitbook.

So I think you should update the wiki in the gitbook.

**Comment by kazupon** [comment] 2017-03-06 10:56
@CommanderXL 
Well, I still could not publish documentation for v6.0.0-alpha.
I’m working on it for official v6.0.0

If you want to check vue-i18n v6.0.0-alpha, you need to refer the [examples](https://github.com/kazupon/vue-i18n/tree/dev/examples)

**Comment by Teddy-Schmitz** [comment] 2017-03-06 12:38
Hi I had the same problem and it was a problem with vuejs-devtools
https://github.com/vuejs/vue-devtools/issues/271
I fixed it by adding an empty computed object to my component.

**Comment by abellion** [comment] 2017-03-06 18:34
The alpha release seems to be tagged on the wrong commit : 

- Release commit : https://github.com/kazupon/vue-i18n/commit/ecfd4018a385fee8daec585d7dece8ae6e5676b0
- Commit name with "release" : https://github.com/kazupon/vue-i18n/commit/3da97ce159ff3ad15e14b38c1cd8ee67c4285c85 Which is ahead

And the vue 2.2 compatibility fix is in https://github.com/kazupon/vue-i18n/commit/5e7bf5e2fa4a52923116c6d172d49632f303523d which is also ahead of the release commit

**Comment by WangShayne** [comment] 2017-03-07 01:49
@kazupon 
Please check this demo
https://github.com/WangShayne/debugForVue-i18n

and
> when I switch the path

I recorded a gif
![1](https://cloud.githubusercontent.com/assets/17644818/23638231/4495151e-031b-11e7-9219-b427fedfb6e5.gif)

**Comment by kazupon** [comment] 2017-03-07 05:06
@WangShayne 
Thank you very much :bow:
I'll try to check and reproduce your repo.

**Comment by kazupon** [comment] 2017-03-08 05:14
@WangShayne 
I could not reproduce your repo... 😞 

I release v6.0.0-alpha.3, and add debug info & improvement.
https://github.com/kazupon/vue-i18n/releases/tag/v6.0.0-alpha.3

Could you try it please?

**Comment by vhuerta** [comment] 2017-03-08 05:53
i still getting the same issue with v6.0.0-alpha.3 

`locale is not a function`

**Comment by WangShayne** [comment] 2017-03-08 05:55
@kazupon
I have a new issue with  v6.0.0-alpha.3
``` Failed in $t due to not find VueI18n instance ```
![2](https://cloud.githubusercontent.com/assets/17644818/23691974/c867631a-0406-11e7-8050-032f28fc85fd.gif)

**Comment by DWYW** [comment] 2017-03-08 11:14
**app.js**
`import i18n from './i18n/index.js'
new Vue({
  ...,
  i18n
})`


**i18n/index.js**

`import Vue from 'vue'
import VueI18n from 'vue-i18n'

Vue.use(VueI18n)

export default new VueI18n({
  locale: "ja",
  messages: {
    "en": {
      "message": {
           "hello": "hello world"
      }
    }
  }
})`

[点这里](https://github.com/DWYW/vue-vuex-vueRouter-vueI18n)

**Comment by vhuerta** [comment] 2017-03-08 17:19
@DWYW thanks for the example, i tried this and now is working like a charm, i was trying with the previous version.

Regards

**Comment by kazupon** [comment] 2017-03-09 02:33
@WangShayne 
I have one additional request. 🙏 
Could you provide node_modules version (vue/vue-router/vuex/vue-loader/vue-template-compiler...) with the below command please?

```sh
$ npm ls --depth=0
```

**Comment by WangShayne** [comment] 2017-03-09 02:42
@kazupon 
Here  :sun_with_face: 
Hope useful
```
+-- express@4.14.1
+-- extract-text-webpack-plugin@1.0.1
+-- fastclick@1.0.6
+-- file-loader@0.9.0
+-- friendly-errors-webpack-plugin@1.1.3
+-- function-bind@1.1.0
+-- html-webpack-plugin@2.28.0
+-- http-proxy-middleware@0.17.3
+-- inject-loader@2.0.1
+-- json-loader@0.5.4
+-- karma@1.4.1
+-- karma-coverage@1.1.1
+-- karma-mocha@1.3.0
+-- karma-phantomjs-launcher@1.0.2
+-- karma-sinon-chai@1.2.4
+-- karma-sourcemap-loader@0.3.7
+-- karma-spec-reporter@0.0.26
+-- karma-webpack@1.8.1
+-- less@2.7.2
+-- less-loader@2.2.3
+-- lolex@1.5.2
+-- mocha@3.2.0
+-- nightwatch@0.9.12
+-- opn@4.0.2
+-- ora@0.3.0
+-- phantomjs-prebuilt@2.1.14
+-- selenium-server@2.53.1
+-- semver@5.3.0
+-- shelljs@0.7.6
+-- sinon@1.17.7
+-- sinon-chai@2.8.0
+-- url-loader@0.5.7
+-- vue@2.1.10
+-- vue-i18n@6.0.0-alpha.3
+-- vue-loader@10.3.0
+-- vue-router@2.2.0
+-- vue-style-loader@1.0.0
+-- vue-template-compiler@2.1.10
+-- vuex@2.1.2
+-- vuex-router-sync@4.1.2 extraneous
+-- vux@2.1.0-rc.43
+-- vux-loader@1.0.35
+-- webpack@1.14.0
+-- webpack-dev-middleware@1.10.0
+-- webpack-hot-middleware@2.16.1
+-- webpack-merge@0.14.1
`-- yaml-loader@0.4.0

npm ERR! extraneous: vuex-router-sync@4.1.2 E:\debugForVue-i18n\node_modules\vuex-router-sync

```

**Comment by yunfengsay** [comment] 2017-03-09 13:44
same issue here....

**Comment by h6ah4i** [comment] 2017-03-09 14:22
Maybe, I have the same issue.

The issue happens when I click a button and it calles `vue-router`'s `push` function inside of the click event handler. Then vue-18n raises the `Failed in $t due to not find VueI18n instance` error. I noticed that the `this` variable points to the `$root` Vue instance (look at the `_name` field in right pane of the screen shot.). I hope it will be helpful for solving the problem. Thanks.

 ![image](https://cloud.githubusercontent.com/assets/2552365/23753786/12320a64-051e-11e7-834b-53da6ac32657.png)

vue: `2.2.1`
vue-router: `2.3.0`
vue-i18n: `6.0.0-alpha.3`

**Comment by kazupon** [comment] 2017-03-10 01:11
@h6ah4i 
Thank you for your reporting! 🙇

**Comment by kazupon** [comment] 2017-03-10 12:56
@h6ah4i 
I have a request. Would you provide the reproducion repos please? 🙏

**Comment by h6ah4i** [comment] 2017-03-10 13:26
@kazupon Sure, but currently I am working on closed source software development, so I will create a small project that can reproduce the issue.

**Comment by kazupon** [comment] 2017-03-10 13:31
@h6ah4i
Thank you very much!! 😭

**Comment by h-collector** [comment] 2017-03-10 18:03
Just wanted to add that in latest version (after commit 891f8ea)
changing ` options.i18n instanceof VueI18n `
to: ` typeName(options.i18n) === 'VueI18n' `
in sources produces a bug if used in tandem with uglifyjs or other minification tools.
Name of function is mangled so we get in production something like ` 'r' ===  'VueI18n' ` ` and end up with undefined this.$i18n

**Comment by 884323767** [comment] 2017-03-11 02:30
same issue with mangle

**Comment by h6ah4i** [comment] 2017-03-11 03:51
@kazupon Hi. I am now trying to reproduce the issue on my codebase but I cannot reproduce it anymore... I guess restarting webpack-dev-server or `yarn install` resolved the issue in my case 🤔

However, #124 is still able to reproduce. Enabling uglify plugin or using minified version of `vue-i18n` causes the issue.

**Comment by kazupon** [comment] 2017-03-11 04:17
Hi everyone!
Thank you for your cooperation.

I could reproduce this issue.
https://jsfiddle.net/w431Lez7/22/

I'll try to fix.

**Comment by kazupon** [comment] 2017-03-12 00:02
I released latest version (v6.0.0-alpha.5)
Please check it.
https://github.com/kazupon/vue-i18n/releases/tag/v6.0.0-alpha.5

**Comment by zce** [comment] 2017-03-12 05:48
Still have this problem when I use the `vuex-router-sync`

**Comment by kazupon** [comment] 2017-03-12 06:19
@zce
Thank you for your reporting!
Could you provide the reproduction repo please?

**Comment by zce** [comment] 2017-03-12 06:34
@kazupon 
I find the problem is not because of `vuex-router-sync`.
Because I used vue-devtools

**Comment by zce** [comment] 2017-03-12 06:51
@kazupon 

https://github.com/zce/vue-i18n/commit/e78b77058ba8620da72aaf04c00d73e7874f23f9

**Comment by h6ah4i** [comment] 2017-03-12 08:39
@kazupon Hi. I have successfully reproduce the bug thanks to @zce 's advice!

https://github.com/h6ah4i/vue-i18n-issue-118-sample

**Comment by kazupon** [comment] 2017-03-12 15:38
@zce @h6ah4i 
Thank you for your reproduction repo & info! 

I think this is vue-devtools issue.
https://github.com/vuejs/vue-devtools/issues/271

**Comment by zce** [comment] 2017-03-12 15:47
👍 I think so

**Comment by steffanhalv** [comment] 2017-03-13 11:04
@kazupon I dont have dev-tools installed, but still I get this issue..

**Comment by kazupon** [comment] 2017-03-14 01:21
@steffanhalv 
Could you provide the minimum reproduction repo please?

**Comment by wannymiarelli** [comment] 2017-03-16 08:59
Same here, devTools removed but still get the same error.

```
import Vue from 'vue'
import VueI18n from 'vue-i18n'
// import all languages
import it from './it.json'
// Setting the base lang
let languages = {
  it: it
}
Vue.use(VueI18n)
Vue.config.lang = 'it'
// set locales
Object.keys(languages).forEach((language) => {
  Vue.locale(language, languages[language])
})

```

**Comment by zce** [comment] 2017-03-16 09:16
@wannymiarelli 
Before the API is deprecated

for 6.x: 
https://github.com/kazupon/vue-i18n/blob/dev/examples/started/index.html

**Comment by wannymiarelli** [comment] 2017-03-16 09:17
@zce God sorry didnt notice this one. My bad.

**Comment by ChangJoo-Park** [comment] 2017-03-21 15:31
Same here with alpha.6 :cry:

**Comment by ChangJoo-Park** [comment] 2017-03-21 15:35
https://github.com/ChangJoo-Park/vue-i18n-error 

Here is my repo

**Comment by kazupon** [comment] 2017-03-22 02:37
@ChangJoo-Park 
Thank you for your reporting and repo providing!
Sorry, my bad.
vue-i18n API is breaking changed!
Please See the docs: 
https://kazupon.github.io/vue-i18n/en/

**Comment by kazupon** [comment] 2017-03-22 02:38
Released v6.0.0-beta.1
Please check it! 
https://github.com/kazupon/vue-i18n/releases/tag/v6.0.0-beta.1

**Comment by ChangJoo-Park** [comment] 2017-03-22 05:40
Thank you @kazupon !! 
I tried v6.0.0-beta.1 with my repo https://github.com/ChangJoo-Park/vue-i18n-error

It works well 😃

**Comment by jeerbl** [comment] 2017-03-22 15:27
I can still reproduce with 6.0.0-beta.1. @ChangJoo-Park how do you create the i18n instance?

**Comment by ChangJoo-Park** [comment] 2017-03-24 09:13
hello @jeerbl please see my repo

https://github.com/ChangJoo-Park/vue-i18n-error

**Comment by jeerbl** [comment] 2017-03-24 09:20
@ChangJoo-Park in the end, as I am using Vuex, I am now using `vuex-i18n`.

Thx anyway
Jerome

**Comment by kazupon** [comment] 2017-04-05 17:49
release v6.0.0
https://github.com/kazupon/vue-i18n/releases/tag/v6.0.0

**Closed by kazupon** 2017-04-05 17:49 UTC
Labels: help repro wanted, need more repro, v6-alpha
