### ISSUE TITLE
Changing locale doesn't work for js files

### ISSUE THREAD

**Issue by DariaYeremina** [kazupon/vue-i18n#1045] opened 2020-11-10 14:31 UTC
**Versions:**
"vue": "^2.6.11",
"vue-i18n": "^8.17.3"

I added i18n in external js file and exported const from that file.
```
import i18n from '@/plugins/i18n';

export const menu = [
    {
        title: i18n.t('navigation.schedule'),
        children: [
            {
                title: i18n.t('navigation.planning'),
                path: '/checkpoint/control_calendar'
            },
            {
                title: i18n.t('navigation.calendar'),
                path: '/checkpoint/control_summary_calendar'
            }
        ]
    },
]
```

Later I imported data in SFC. But When I change locale, data from that js file doesn't change.

**Comment by exoego** [comment] 2020-11-11 07:13
Could you check this document ?
https://kazupon.github.io/vue-i18n/guide/locale.html

**Comment by DariaYeremina** [comment] 2020-11-17 09:03
Yes, I checked that document, but it doesn't work. I switched locale in this way 
```
switchLocale () {
            this.$store.commit('locale/SET_CURRENT_LOCALE', this.buttonTitle);
            this.$store.dispatch('locale/switchLocale');
            this.$vuetify.lang.current = this.currentLocale;
            this.$root.$i18n.locale = this.currentLocale;
        },
```
and have menu array with titles (which uses i18n) in separate js file. But when I try to switch locale, menu doesn't switch.
The same problem I had when I tried to switch locale with `this.$i18n.locale = this.currentLocale;`

**Comment by kazupon** [comment] 2020-11-21 15:56
How is the imported menu handled in the components of SFC?
Are you using in the template via `data` or `computed`?
After that, Could you give us minimal reproduction codes, pelase? 🙏

**Comment by DariaYeremina** [comment] 2020-11-23 08:59
I tried to use menu in `data` and in `computed` as well.
Here is a link with reproduction: https://codesandbox.io/s/hungry-shape-gj14f?file=/src/components/HelloWorld.vue
You can see, in console `this.$root.$i18n.locale` changes on click, but translations don't change

**Comment by kazupon** [comment] 2020-11-24 16:41
Thank you very much!
I'll try to check it!

**Comment by DariaYeremina** [comment] 2020-11-24 18:32
Thank you🙏🏻

**Comment by Huooo** [comment] 2021-01-19 09:06
Is there an answer? I meet the same problem. Main pure js files(eg. constants.js) are called when App is loaded. Then I try to change "i18n.locale" value, constants still show the last locale's message.

**Comment by chenbingchang** [comment] 2021-01-26 06:34
I meet the same problem .

**Comment by chenbingchang** [comment] 2021-01-26 06:34
I meet the same problem .
我遇到了同样的问题

**Comment by rofequl** [comment] 2021-03-01 15:23
I am also face the same problem. What should I do, anyone has any idea??
```
import {i18n} from "@/core/plugins/i18n";
export default [
    {
        _name: 'CSidebarNav',
        _children: [
            {
                _name: 'CSidebarNavItem',
                name: i18n.t('nav.dashboard'),
                to: '/dashboard',
                icon: 'cil-home',
            },
        ]
    }
]
```
```
import Vue from 'vue'
import VueI18n from 'vue-i18n'

import enUS from './lang/en_US'
import bnBD from './lang/bn-BD'

Vue.use(VueI18n)

export const defaultLang = 'en_US'

const messages = {
    'en-US': {
        ...enUS
    },
    'bn-BD': {
        ...bnBD
    }
}
export const i18n = new VueI18n({
    silentTranslationWarn: true,
    locale: defaultLang,
    fallbackLocale: defaultLang,
    messages
})

```

**Comment by major697** [comment] 2021-05-20 13:18
Any ides to fix it?

**Comment by kazupon** [comment] 2021-05-22 14:51
Sorry, for the late reply to your response. :bow:

Unfortunately, the way to use it, in this case, is not to let `i18n.t` evaluated messages change reactively when you change the locale.
because i18n instances use the mechanism of Vue's reactive system.
Vue's reactive system (especially Vue 2.x, but Vue 3, which are designed to work outside Vue components) is generally intended to be used within Vue components.

The workaround is to define a function that is passed an `i18n` instance, and use the evaluated data in computed prop, as in the code I committed at the following URL. 
https://github.com/kazupon/vue-i18n-v8-repro-1045/commit/640edbdaa829ac2a50dc6ad02f3707db40544492

Computed prop works with Vue's reactive system. `i18n.t` evaluated in this function will be tracked in the dependency of Vue's reactive system.

Thanks.

**Closed by kazupon** 2021-05-22 14:51 UTC
Labels: Status: Need More Info

**Comment by DariaYeremina** [comment] 2021-05-24 06:34
@kazupon thank you for you help
