### ISSUE TITLE
vue-i18n and  iview 

### ISSUE THREAD

**Issue by kuailingmin** [kazupon/vue-i18n#222] opened 2017-09-07 09:15 UTC
import iView from 'iview';
import VueI18n from 'vue-i18n'
Vue.use(VueI18n)
Vue.use(iView)

but run in browser!!! 
     Error in render function: "TypeError: __WEBPACK_IMPORTED_MODULE_2_vue__.default.locale is not a function"

[vue-i18n] Value of key 'i.select.noMatch' is not a string!
[vue-i18n] Cannot translate the value of keypath 'i.select.noMatch'. Use the value of keypath as default
[vue-i18n] Value of key 'i.select.loading' is not a string!

Why?

**Comment by kazupon** [comment] 2017-09-07 10:18
Thank you for your reporting!

Could you provide reproduction minimum code with github repo please?
I would like to reproduce it. 😉

**Comment by kuailingmin** [comment] 2017-09-07 11:52
@kazupon  Ok!    please git clone https://github.com/kuailingmin/myObject.git   

step： 
     1.  npm  i
     2. npm run hot

please help me！Thank you！

**Comment by javady** [comment] 2017-09-07 15:54
what version do you use? use 5.0x is no problem `"vue-i18n": "^5.0.3",`

**Comment by kuailingmin** [comment] 2017-09-08 04:34
@javady    Thank you！ my question has been resolved 

Vue.use(iView, {
    i18n: (key, value) => i18n.vm._t(key, value)
})

**Comment by fjonas** [comment] 2017-10-13 16:51
@kuailingmin Thank you! I had the same problem and resolved by borrowing your codes.

**Comment by fjonas** [comment] 2017-10-17 01:52
@kazupon I think this issue can be closed. This issue was caused by `iview` 's integration in `vue-i18n` and `iview` users have not read `iview` docs carefully.

**Comment by kazupon** [comment] 2017-10-17 02:01
@fjonas 
okay thanks!

**Closed by kazupon** 2017-10-17 02:01 UTC
Labels: need more repro
