### ISSUE TITLE
TypeError: Cannot redefine property: $i18n

### ISSUE THREAD

**Issue by HadiChen** [kazupon/vue-i18n#421] opened 2018-09-03 07:06 UTC
### vue & vue-i18n version
ex: 2.5.17, 8.0.0
vue:2.5.17
vue-i18n:8.0.0
nuxt.js:1.4.2
### What is Expected?

![image](https://user-images.githubusercontent.com/11555571/44972013-4737ff80-af8a-11e8-8bb3-85c13725fb05.png)

### What is actually happening?

https://github.com/kazupon/vue-i18n/blob/170f69109a4e655af607c20bea87b51ab04a16d1/src/extend.js#L5

```JavaScript
  Object.defineProperty(Vue.prototype, '$i18n', {
    get () { return this._i18n }
  })
```
fix bug edit
```JavaScript
if (!Vue.prototype.hasOwnProperty('$i18n')) {
  Object.defineProperty(Vue.prototype, '$i18n', {
    get () { return this._i18n }
  })
}
```

**Comment by BorjaRafols** [comment] 2018-09-13 14:45
I can confirm that this fixes the problem, any idea on when it will get merged into master?

**Comment by jgribonvald** [comment] 2018-09-18 10:39
Me too I confirm this solve the problem !

**Comment by kazupon** [comment] 2018-09-25 07:18
@jgribonvald
Hi!
sorry for my late response.

There is a possibility that this problem is caused by the vue-i18n build setting problem.

kazupon/vue-i18n@1a1958a

Would you be able to try to use the dist files (dist/*.js) that build with build confg of dev branch please?
https://kazupon.github.io/vue-i18n/installation.html#dev-build

**Comment by jgribonvald** [comment] 2018-09-25 11:32
@kazupon 
Hi and thanks to respond !
Else I'm sorry this doesn't change anything:
```
TypeError: can't redefine non-configurable property "$i18n"
ObjectOrReflectDefineProperty ...
defineProperty ...
extend ...
install ...
$n.use https://unpkg.com/vue@2.5.17/dist/vue.min.js:6:34186
__webpack_require__ ...
<anonyme> ...
<anonyme> ...
InnerModuleEvaluation  ...
ModuleEvaluate ...
```

**Comment by jgribonvald** [comment] 2018-09-26 17:54
@kazupon sorry for the delay
Nothing better, here is the trace of the error:
```
Uncaught TypeError: Cannot redefine property: $i18n
    at Function.defineProperty (<anonymous>)
    at extend (...)
    at Function.install (...)
    at Function.$n.use (VM169 vue.min.js:6)
    at Module.5a74
 ```

**Comment by kazupon** [comment] 2018-09-28 06:02
@jaredzhu1993 
Hi!

I found the strange javascript codes in your jsfiddle reproduction.
In javascript of jsfiddle, VueI18n had been doubly bundled. 🤔 

Could you provide the minimum reproduction codes with **repository** please? 🙏

**Comment by jgribonvald** [comment] 2018-10-09 16:33
In my mind the problem is that we have 2 web components (that are 2 repositories) including their dependency of vue-i18n, and so as it's builded and loaded separately they try to load twice vue-i18n whereas there is only on vuejs instance.
I'm not really competent in this part, but that i can say is that the fix 
```
if (!Vue.prototype.hasOwnProperty('$i18n')) {
  Object.defineProperty(Vue.prototype, '$i18n', {
    get () { return this._i18n }
  })
}
```

is working ! It means that it check that vue-i18n isn't already registered into vuejs.

On an other side why not having an independant plugin ? used as a service...

**Comment by kazupon** [comment] 2018-10-12 09:52
I have released v8.1.1
please try it.

**Comment by jgribonvald** [comment] 2018-10-12 13:56
this doesn't not solve the problem
vue-i18n should manage several web-components (and not related/on same project ) trying each one to configure $i18n attribute on their own : ```TypeError: can't redefine non-configurable property "$i18n"```
After it was setted all components trying to do the same configuration will get the error

**Closed** 2018-10-14 17:34 UTC
Labels: bug

**Comment by jgribonvald** [comment] 2018-10-15 08:46
@kazupon : thanks a lot !
